<a href="https://colab.research.google.com/github/tgomes078/Numpy/blob/master/Python_Machine_Learning_Third_Edition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Curso de Numpy

In [11]:
# Introdução Numpy
import numpy as np

# Criação de uma lista em Python
lst = [[1,2,3],
       [4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [12]:
# Lista em Numpy
ary1d = np.array(lst)
ary1d

array([[1, 2, 3],
       [4, 5, 6]])

Figura 1 - Inlustração de uma matriz bidimensional Numpy

![Figura 1 - Inlustração de uma matriz bidimensional Numpy](https://raw.githubusercontent.com/tgomes078/Numpy/master/Figura1-Inlustra%C3%A7%C3%A3o_de_uma_matriz_bidimensional_Numpy.png)

In [13]:
# Tipo de dados da Matriz
ary1d.dtype

dtype('int64')

In [14]:
# Alteração do tipo de dados da Matriz
float32_ary = ary1d.astype(np.float32)
float32_ary

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [15]:
float32_ary.dtype

dtype('float32')

In [16]:
# Verificando o tamanho em bits do array Numpy
ary2d = np.array([[1, 2, 3],
                  [4, 5, 6]], dtype='int64')
ary2d.itemsize

8

In [17]:
# Identifica a quantidade de elementos de uma Matriz
ary2d.size

6

In [18]:
# Identifica a quantidade de dimensões que a Matriz possui
ary2d.ndim

2

In [19]:
# Identifica o número de eixos de uma Matriz (Linhas,Colunas)
ary2d.shape

(2, 3)

In [20]:
# Identifica a quantidade de columas de uma matriz dimensional
# O Shape é sempre uma tupla
np.array([1, 2, 3]).shape

(3,)

In [21]:
# Também podemos fornecer um único ponto flutuante ou número inteiro, que construirá um zero-dimensional
array
scalar = np.array(5)
scalar

array(5)

In [22]:
scalar.ndim

0

In [23]:
scalar.shape

()

A função array funciona com a maioria dos iterables no Python, incluindo listas, tuplas e objetos de intervalo; no entanto, a matriz não suporta expressões de gerador. Se queremos analisar geradores diretamente, no entanto, podemos usar a função **fromiter**, conforme demonstrado abaixo

In [26]:
def generator():
    for i in range(10):
        if i % 2:
            yield i
gen = generator()
np.fromiter(gen, dtype=int)

array([1, 3, 5, 7, 9])

In [27]:
  gen

<generator object generator at 0x7f310f406990>

In [30]:
# Usando 'comprehensions' a seguinte expressão do gerador é equivalente ao code {generator} acima
generator_expression = (i for i in range(10) if i % 2)
np.fromiter(generator_expression, dtype=int)

array([1, 3, 5, 7, 9])

In [31]:
generator_expression

<generator object <genexpr> at 0x7f310db61af0>

In [32]:
# Criação de uma matriz de três linhas e três colunas com o número um (1)
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# Criação de uma matriz de três linhas e três colunas com o número zero (0)
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# Retorne uma matriz 2-D com as na diagonal e zeros em outro lugar.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# Extraia uma diagonal ou construa uma matriz diagonal.
np.diag((3, 3, 3))

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

## 1.

In [0]:
import numpy as np
class Perceptron(object):
    """Perceptron classifier.
    
    Parameters
    ------------
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight 
      initialization.
    
    Attributes
    -----------
    w_ : 1d-array
      Weights after fitting.
    errors_ : list
      Number of misclassifications (updates) in each epoch.
    
    """
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
    
    def fit(self, X, y):
        """Fit training data.
        
        Parameters
        ----------
        X : {array-like}, shape = [n_examples, n_features]
          Training vectors, where n_examples is the number of 
          examples and n_features is the number of features.
        y : array-like, shape = [n_examples]
          Target values.
        
        Returns
        -------
        self : object
        
        """
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01,
                              size=1 + X.shape[1])
        self.errors_ = []
        
        for _ in range(self.n_iter):
            errors = 0
            for xi, target in zip(X, y):
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self
    
    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]
    
    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

## 3. Construindo bons conjuntos de dados de treinamento -  pré-processamento de dados

Decision trees (Árvores de decisão) e Random forests (Florestas aleatórias) são duas das poucas algoritmos de aprendizagens de máquina onde não precisamos nos preocupar com o dimensionamento de recursos. Esses algoritmos são invariáveis ​​em escala.